<?php

namespace AppBundle\Repository;

/**
 * BatterieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatterieRepository extends \Doctrine\ORM\EntityRepository
{
}
