<?php

namespace AppBundle\Repository;

/**
 * CasTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasTestRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * Liste des recettes à faire triées de manière à avoir celles qui ne
     * sont pas encore recettées et puis par ordre de création d'une
     * manière décroissante
     * @return array
     */
    public function getRecettes()
    {
        $qB = $this->createQueryBuilder('c');
        $qB->orderBy('c.critereSuccesEchec', 'ASC')
                ->addOrderBy('c.id', 'DESC');
        
        $qry = $qB->getQuery();
        
        return $qry->getResult();
    }
    
}
