<?php

namespace AppBundle\Repository;

/**
 * CritereSuccesEchecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CritereSuccesEchecRepository extends \Doctrine\ORM\EntityRepository
{
}
