<?php

namespace AppBundle\Repository;

/**
 * PrerequisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrerequisRepository extends \Doctrine\ORM\EntityRepository
{
}
