parameters:
    database_host: www.db4free.net
    database_port: null
    database_name: thierry1804
    database_user: thierry1804
    database_password: 184BrianNeptunia
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: thierry1804@gmail.com
    mailer_password: null
    secret: CCFE0D906B0FAA19514F01556A7A1FDF3BC23BFE5C31D112B30C363DA7053C46
