parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: cahier
    database_user: dev-md
    database_password: Dev674.
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: thierry1804@gmail.com
    mailer_password: null
    secret: CCFE0D906B0FAA19514F01556A7A1FDF3BC23BFE5C31D112B30C363DA7053C46
